[project]
name = "nexora-uv"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.115.8",
    "uvicorn>=0.34.0",
    "openai>=1.0.0",
    "python-dotenv>=1.0.1",
    "pydantic>=2.0.0",
    "httpx>=0.28.1"
]

